version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_DOMAIN=backend
      - TEMP_DIR=/app/temp
    volumes:
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_PORT=8000
      - API_DOMAIN=backend
    depends_on:
      - backend